[package]
name = "bcr-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = { git = "https://github.com/BitcreditProtocol/nostr.git", features = [
  "nip59",
] }
nostr-relay-builder = { git = "https://github.com/BitcreditProtocol/nostr.git", branch = "sqldb" }
nostr-sqldb = { git = "https://github.com/BitcreditProtocol/nostr.git", branch = "sqldb", features = [
  "postgres",
] }
tokio = "1.44.1"
axum = { version = "0.8.3", features = ["ws", "tokio"] }
axum-raw-websocket = { git = "https://github.com/tompro/axum-raw-websocket.git" }
anyhow = "1.0.97"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tower-http = { version = "0.6.2", features = ["set-header"] }
clap = { version = "4.5.29", features = ["derive", "env"] }
