[package]
name = "bcr-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = { version = "0.40", features = ["nip59"] }
nostr-relay-builder = { version = "0.40" }
tokio = "1.44.1"
axum = { version = "0.8.3", features = ["ws"] }
anyhow = "1.0.97"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
