[package]
name = "bcr-relay"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
nostr-sdk = { git = "https://github.com/BitcreditProtocol/nostr.git", features = [
  "nip59",
] }
nostr = { git = "https://github.com/BitcreditProtocol/nostr.git" }
nostr-relay-builder = { git = "https://github.com/BitcreditProtocol/nostr.git", branch = "sqldb" }
nostr-sqldb = { git = "https://github.com/BitcreditProtocol/nostr.git", branch = "sqldb", features = [
  "postgres",
] }
tokio = "1.44.1"
axum = { version = "0.8.3", features = ["ws", "tokio"] }
axum-raw-websocket = { git = "https://github.com/tompro/axum-raw-websocket.git" }
anyhow = "1.0.97"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tower-http = { version = "0.6.2", features = ["cors"] }
clap = { version = "4.5.29", features = ["derive", "env"] }
chrono = "0.4.41"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
tokio-postgres = "0.7.13"
deadpool-postgres = "0.14.1"
