name: Rust CI

on:
  push:
    branches: [ "*" ]

permissions:
  contents: read
  security-events: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          docker system prune -a -f
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          sudo apt-get autoremove -y
          echo "After cleanup:"
          df -h

      - name: Switch rust version
        run: rustup default stable

      - name: Update rust
        run: rustup update

      - name: Cargo update
        run: cargo update --verbose

      - name: Check
        run: cargo check --verbose

      - name: Add fmt
        run: rustup component add rustfmt

      - name: Add cargo deny
        run: cargo install cargo-deny

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Test
        run: cargo test
        continue-on-error: true

      - name: Build
        run: cargo build --verbose

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Add clippy
        run: rustup component add clippy

      - name: Clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Cargo deny
        run: cargo deny check
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
