name: Test coverage

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read
  security-events: write

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          docker system prune -a -f
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          sudo apt-get autoremove -y
          echo "After cleanup:"
          df -h

      - name: Switch rust version
        run: rustup default stable

      - name: Update rust
        run: rustup update stable

      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview

      - name: Activate cache
        uses: Swatinem/rust-cache@v2.8.0
        with:
          prefix-key: "bcr-relay"

      - name: Install grcov
        uses: taiki-e/install-action@v2
        with:
          tool: grcov

      - name: run tests
        run: cargo test --workspace --verbose
        env:
          LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
          RUSTFLAGS: "-Cinstrument-coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: BitcreditProtocol/bcr-relay
